services:
  mineru-api:
    # 从 Dockerfile 构建包含 COS 支持的镜像
    build:
      context: .
      dockerfile: Dockerfile
    image: mineru-cos:latest
    container_name: mineru-api-cos
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      # 挂载配置文件
      - ./config:/app/config:ro
      # 输出目录
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      MINERU_MODEL_SOURCE: local
      MINERU_ENABLE_COS: "true"
      MINERU_COS_CONFIG: /app/config/cos_config.json
    entrypoint: mineru-api
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    networks:
      - mineru-network

networks:
  mineru-network:
    driver: bridge
    name: mineru-cos-net